export const ANILIST_MEDIA_INFO_TAG = 'ANILIST_MEDIA_INFO';
export const ANILIST_USERS_INFO_TAG = 'ANILIST_USERS_INFO';
export const ANILIST_CHARACTERS_TAG = 'ANILIST_CHARACTERS';

export const ANILIST_TAGS = [
    ANILIST_MEDIA_INFO_TAG,
    ANILIST_USERS_INFO_TAG,
    ANILIST_CHARACTERS_TAG,
];